[project]
name = "bench"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=4.0.0",
    "memory-profiler>=0.61.0",
    "psutil>=7.0.0",
    "tqdm>=4.67.1",
]

[project.scripts]
ybbb = "ybbb.cli:main"